# Generated by Django 5.1.2 on 2024-10-29 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='ingtemp_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Temporada', to='ingredientes.temporadas'),
        ),
    ]
