# Generated by Django 5.1.2 on 2024-10-30 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredientes", "0002_alter_ingredientes_ingtemp_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientes",
            name="ingtemp_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredientes.temporadas",
            ),
        ),
    ]
