# Generated by Django 5.1.2 on 2024-10-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0003_alter_ingredientes_ingtemp_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catnom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dificultades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difnom', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='temporadas',
            name='tempnom',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recnom', models.CharField(max_length=40)),
                ('recela', models.CharField(max_length=400)),
                ('rectem', models.IntegerField(default=0)),
                ('reccat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.categorias')),
                ('recdif_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.dificultades')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientesRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrecpes', models.PositiveSmallIntegerField(default=0)),
                ('ingrecing_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes')),
                ('ingrecrec_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.recetas')),
            ],
        ),
    ]
