# Generated by Django 5.0.9 on 2024-11-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredientes', '0006_alter_categorias_catnom_alter_dificultades_difnom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='catnom',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dificultades',
            name='difnom',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='ingnom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ingredientes',
            name='ingtemp_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.temporadas'),
        ),
        migrations.AlterField(
            model_name='ingredientesrecetas',
            name='ingrecing_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.ingredientes'),
        ),
        migrations.AlterField(
            model_name='ingredientesrecetas',
            name='ingrecrec_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.recetas'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='reccat_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.categorias'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='recdif_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredientes.dificultades'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='recela',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='recnom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='rectem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporadas',
            name='tempnom',
            field=models.CharField(max_length=9),
        ),
    ]
