# Generated by Django 5.1.3 on 2024-11-07 14:29

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factcli', models.CharField(max_length=50, verbose_name='Cliente')),
                ('factfec', models.DateField(verbose_name='Fecha Factura')),
                ('factest', models.CharField(choices=[('V', 'Vencida'), ('C', 'Cobrada'), ('P', 'Pendiente')], max_length=1, verbose_name='Estado')),
                ('factdir', models.CharField(max_length=50, verbose_name='Direccion')),
                ('factmai', models.EmailField(max_length=254, verbose_name='Mail de contacto')),
                ('factcre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('factmod', models.DateTimeField(auto_now=True, verbose_name='Fecha modifica')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dettip', models.CharField(choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('3', 'Tipo 3')], max_length=6, verbose_name='Producto Tipo')),
                ('detnom', models.CharField(max_length=50, verbose_name='Producto')),
                ('detpre', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('detiva', models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('detpre'), '*', models.Value(0.21)), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualfact.facturas')),
            ],
        ),
    ]
