# Generated by Django 4.1 on 2024-11-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factcli', models.CharField(max_length=50, verbose_name='Cliente')),
                ('factfec', models.DateField(verbose_name='Fecha Factura')),
                ('factest', models.CharField(choices=[('V', 'Vencida'), ('C', 'Cobrada'), ('P', 'Pendiente')], max_length=1, verbose_name='Estado')),
                ('factdir', models.CharField(max_length=50, verbose_name='Direccion')),
                ('factmai', models.EmailField(max_length=254)),
                ('factcre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('factmod', models.DateTimeField(auto_now=True, verbose_name='Fecha modifica')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dettip', models.CharField(choices=[('1', 'Tipo1'), ('2', 'Tipo2'), ('3', 'Tipo3')], max_length=6)),
                ('detnom', models.CharField(max_length=50, verbose_name='Cliente')),
                ('detpre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visuafact.facturas')),
            ],
        ),
    ]
